data<-read.csv("household_power_consumption.csv",header = TRUE)
subSetData <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(subSetData$Date, subSetData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalActivePower<-as.numeric(subSetData$Global_active_power)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datetime, globalActivePower, type="l", xlab="", ylab="Global Active Power (kilowatts)")
Voltage<-as.numeric(subSetData$Voltage)
plot(datetime, Voltage, type="l", xlab="datetime", ylab="Voltage")
SubMetering1<-as.numeric(subSetData$Sub_metering_1)
SubMetering2<-as.numeric(subSetData$Sub_metering_2)
SubMetering3<-as.numeric(subSetData$Sub_metering_3)
plot(datetime, SubMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, SubMetering2, type="l", col="red")
lines(datetime, SubMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
GlobalReactivePower<-as.numeric(subSetData$Global_reactive_power)
plot(datetime,GlobalReactivePower, type="l", xlab="ddatetime", ylab="Global_reactive_power")
dev.off()